{% set name = "meson-python" %}
{% set version = "0.20.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 6d9726ae6cd37e22f210c74b364b30180a68c20442e97ff09f3c566a414af738

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<315 or py>=316]

requirements:
  host:
    - pip
    - python
    - meson >=0.64.0  # [py<312]
    - meson >=1.2.3  # [py>=312]
    - packaging >=23.2  # [not osx]
    - packaging >=24.2  # [osx]
    - pyproject-metadata >=0.9.0
    - tomli >=1.0.0     # [py<311]
    # mesonpy takes care of creating the wheels without using
    # wheel. See
    # https://github.com/mesonbuild/meson-python/blob/main/mesonpy/_wheelfile.py
    - setuptools
    # meson-python: error: Could not find ninja version 1.8.2 or newer.
    - ninja-base >=1.8.2
  run:
    - python
    - meson >=0.64.0  # [py<312]
    - meson >=1.2.3  # [py>=312]
    - packaging >=23.2  # [not osx]
    - packaging >=24.2  # [osx]
    - pyproject-metadata >=0.9.0
    - tomli >=1.0.0     # [py<311]

{% set tests_to_skip = "" %}
{% set tests_to_skip = tests_to_skip + "test_tags.py" %}                      # [unix or win]
{% set tests_to_skip = tests_to_skip + " or test_wheel.py" %}                 # [win]
{% set tests_to_skip = tests_to_skip + " or test_editable_install" %}         # [win]
{% set tests_to_skip = tests_to_skip + " or test_editble_reentrant" %}        # [win]
{% set tests_to_skip = tests_to_skip + " or test_editable_verbose" %}         # [win]
{% set tests_to_skip = tests_to_skip + " or test_spam" %}                     # [win]

# Dependency returns slightly different text than expected, but meaning is the same.
{% set tests_to_skip = tests_to_skip + " or test_missing_version" %}          # [win]
{% set tests_to_skip = tests_to_skip + " or test_no_pep621" %}                # [win]
{% set tests_to_skip = tests_to_skip + " or test_pep621" %}                   # [win]
{% set tests_to_skip = tests_to_skip + " or test_dynamic_version" %}          # [win]
{% set tests_to_skip = tests_to_skip + " or test_install_data" %}             # [win]

# The following fail: assert 'macosx_10_9_x86_64' == 'macosx_10_16_x86_64'
# (or _arm64 on the builders -- it works locally)
{% set tests_to_skip = tests_to_skip + " or test_scipy_like" %}               # [osx]
{% set tests_to_skip = tests_to_skip + " or test_detect_wheel_tag_module" %}  # [osx]
{% set tests_to_skip = tests_to_skip + " or test_detect_wheel_tag_script" %}  # [osx]
{% set tests_to_skip = tests_to_skip + " or test_limited_api" %}              # [osx]
{% set tests_to_skip = tests_to_skip + " or test_limited_api_disabled" %}     # [osx]

# Gets a SIGKILL on the builders
{% set tests_to_skip = tests_to_skip + " or test_local_lib" %}                # [osx and arm64]

test:
  imports:
    - mesonpy
  source_files:
    - tests/
    - docs/
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    # cython required for Python 3.12 support, see
    # https://github.com/mesonbuild/meson-python/commit/936eee3fddfda34cbbb690acec8a170d089c1770
    - cython >=3.0.3
    - git
    - gitpython
    - patchelf   # [linux]
    - pkgconfig  # [linux]
    - pip
    - pytest >=6.0
    - pytest-mock
    # see https://github.com/mesonbuild/meson-python/commit/424f2f97e00c5281437355acd1232d29431dcf23
    - typing-extensions >=3.7.4  # [py<311]
    - wheel
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja-base >=1.8.2
    - cmake
  commands:
    - pip check
    # CPPFLAGS exports -DNDEBUG which is unwanted
    - export CPPFLAGS=${CPPFLAGS//-DNDEBUG/}  # [unix]
    # tests are relevant to wheel and not conda packages
    - pytest tests -vv -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/mesonbuild/meson-python
  dev_url: https://github.com/mesonbuild/meson-python
  doc_url: https://mesonbuild.com/meson-python
  summary: Meson Python build backend (PEP 517)
  description: |
    Python build backend (PEP 517) for Meson projects.
    It enables Python package authors to use Meson as the build backend for their packages.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
  skip-lints:
    - python_build_tool_in_run
    - build_tools_must_be_in_build
    - missing_wheel
