{% set version = "0.12.1" %}
{% set name = "meson-python" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/meson_python-{{ version }}.tar.gz
  sha256: 3d5b3e581d70a58a97b9c116a75e97a76cc4b4c7e75fa0658fc8392371e2f2c2

build:
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - meson >=0.63.3
    - ninja
    - pip
    - wheel
    - setuptools
    - python
    - pyproject-metadata >=0.6.1
    - tomli >=1.0.0  # [py<311]
    - typing-extensions >=3.7.4  # [py<310]
  run:
    - colorama # [win]
    - meson >=0.63.3
    - ninja
    - pyproject-metadata >=0.6.1
    - python
    - tomli >=1.0.0
    - typing-extensions >=3.7.4 # [py<310]

test:
  imports:
    - mesonpy
  commands:
    - pip check
    - pytest tests -vv -k "not (test_contents_unstaged or test_wheel.py or test_pep518 or test_tag or test_detect_wheel_tag or test_spam)" # tests are relevant to wheel and not conda packages
  source_files:
    - tests/
    - docs/
  requires:
    - {{ compiler('c') }}
    - git
    - gitpython
    - patchelf  # [linux]
    - pkgconfig # [linux]
    - pip
    - pytest
    - pytest-mock
    - pyproject-metadata
about:
  home: https://github.com/mesonbuild/meson-python
  dev_url: https://github.com/mesonbuild/meson-python
  doc_url: https://meson-python.readthedocs.io/
  summary: Meson Python build backend (PEP 517)
  description: |
    Python build backend (PEP 517) for Meson projects.
    It enables Python package authors to use Meson as the build backend for their packages.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
