{% set version = "0.12.0" %}
{% set name = "meson-python" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/meson_python-{{ version }}.tar.gz
  sha256: 8cb159a8093a2e73cfa897f8092ec93b74e3842f94dff7fde381c6fe0e0b064d

build:
  skip: True # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - meson 0.64.1
    - pyproject-metadata 0.6.1
    - pip
    - wheel
    - python
    - tomli 1.2.2
    - typing-extensions 3.7.4.2 # [py<38]
  run:
    - colorama # [win]
    - meson >=0.63.3
    - pyproject-metadata >=0.5.0
    - python
    - tomli >=1.0.0
    - typing-extensions >=3.7.4 # [py<38]

test:
  imports:
    - mesonpy
  commands:
    - pip check
    # PEP 518 tests fail with conda because the pyproject.toml and setup.py files are not available in the test environment
    - pytest tests -vv -k "not test_pep518"
  source_files:
    - tests/
    - docs/
  requires:
    - {{ compiler('c') }}
    - cython
    - git
    - gitpython
    - patchelf  # [linux]
    - pip
    - pytest >=6.0
    - pytest-mock

about:
  home: https://github.com/mesonbuild/meson-python
  dev_url: https://github.com/mesonbuild/meson-python
  doc_url: https://meson-python.readthedocs.io/
  summary: Meson Python build backend (PEP 517)
  description: |
    Python build backend (PEP 517) for Meson projects.
    It enables Python package authors to use Meson as the build backend for their packages.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
