{% set version = "0.7.0" %}

package:
  name: meson-python
  version: {{ version }}

source:
  url: https://github.com/FFY00/meson-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 63516ad7ada4721c3c23d7fce396d5aa9d5248b134077d5fd782c40ca803c5ee
  patches:
    - patches/0001-fix-overdependency-on-ninja.patch

build:
  skip: True # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - meson >=0.62.0
    - ninja
    - pyproject-metadata >=0.5.0
    - pip
    - python
    - tomli >=1.0.0
    - typing-extensions >=3.7.4 # [py<38]
  run:
    - colorama # [win]
    - meson >=0.60.0
    - ninja
    - pyproject-metadata >=0.5.0
    - python
    - tomli >=1.0.0
    - typing-extensions >=3.7.4 # [py<38]
    - wheel >=0.36.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    - pytest tests -vv -k "not test_contents_unstaged"
  source_files:
    - tests/
  requires:
    - {{ compiler('c') }}
    - git
    - gitpython
    - patchelf  # [linux]
    - pkgconfig # [linux]
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/FFY00/meson-python
  dev_url: https://github.com/FFY00/meson-python
  doc_url: https://meson-python.readthedocs.io/
  summary: Meson Python build backend (PEP 517)
  description: |
    Python build backend (PEP 517) for Meson projects.
    It enables Python package authors to use Meson as the build backend for their packages.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
