{% set version = "0.11.0" %}
{% set name = "meson-python" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/meson_python-{{ version }}.tar.gz
  sha256: 110258837c2ffe762f5f855c7ea5385f1edd44074e93a0f317ffefc7aab42b09
  patches:
    - patches/0001-fix-overdependency-on-ninja.patch

build:
  skip: True # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - meson 0.64.1
    - ninja
    - pyproject-metadata >=0.5.0
    - pip
    - wheel
    - python
    - tomli >=1.0.0
    - typing-extensions >=3.7.4 # [py<38]
  run:
    - colorama # [win]
    - meson >=0.60.0
    - ninja
    - pyproject-metadata >=0.5.0
    - python
    - tomli >=1.0.0
    - typing-extensions >=3.7.4 # [py<38]
    - wheel >=0.36.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    - pytest tests -vv -k "not test_contents_unstaged"
  source_files:
    - tests/
  requires:
    - {{ compiler('c') }}
    - git
    - gitpython
    - patchelf  # [linux]
    - pkgconfig # [linux]
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/FFY00/meson-python
  dev_url: https://github.com/FFY00/meson-python
  doc_url: https://meson-python.readthedocs.io/
  summary: Meson Python build backend (PEP 517)
  description: |
    Python build backend (PEP 517) for Meson projects.
    It enables Python package authors to use Meson as the build backend for their packages.
  license: MIT
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
